name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Setup Java for Android builds
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Setup Flutter with specific version 3.27.1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:" # Ensures cache is version-specific

      # Debugging: Verify Flutter installation
      - name: Verify Flutter version
        run: flutter --version

      # Get dependencies
      - name: Install dependencies
        run: flutter pub get

      # Debugging: Check pubspec.lock
      - name: List dependencies
        run: flutter pub deps
        if: failure() # Runs only if previous step fails

      # Analyze the code
      - name: Analyze code
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test

      # Build APK
      - name: Build APK
        run: flutter build apk --release --split-per-abi
        continue-on-error: true # Allows workflow to continue even if this fails

      # Upload APK artifact (if built successfully)
      - name: Upload APK
        uses: actions/upload-artifact@v3
        if: success() # Only if previous steps succeed
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/*.apk

      # Build App Bundle
      - name: Build App Bundle
        run: flutter build appbundle --release
        continue-on-error: true

      # Upload App Bundle artifact (if built successfully)
      - name: Upload App Bundle
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: app-bundle
          path: build/app/outputs/bundle/release/*.aab
