name: Flutter CI/CD with Firebase

on:
  push:
    branches:
      - main # or your preferred branch for CI/CD deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.0" # Use the desired Flutter version

      # Install dependencies using flutter pub get
      - name: Install dependencies
        run: |
          flutter pub get  # This is the correct command for Flutter projects

      # Run Flutter tests (optional but recommended)
      - name: Run Flutter tests
        run: |
          flutter test

      # Build the app
      - name: Build Flutter App (Release)
        run: |
          flutter build apk --release # Or for iOS: flutter build ios --release

      # Set up Firebase CLI
      - name: Set up Firebase CLI
        uses: wzieba/Firebase-CLI-Github-Action@v2
        with:
          firebase_token: ${{ secrets.FIREBASE_AUTH_TOKEN }} # Add your Firebase Auth Token in GitHub secrets

      # Deploy to Firebase Hosting (for web app)
      - name: Deploy to Firebase Hosting (Web)
        run: |
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_AUTH_TOKEN }}
