name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Setup Java for Android builds
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Setup Flutter with specific version 3.27.1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
          channel: "stable"
          cache: true

      # Get dependencies using flutter pub get
      - name: Install dependencies
        run: flutter pub get

      # Analyze the code
      - name: Analyze code
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test

      # Build APK
      - name: Build APK
        run: flutter build apk --release --split-per-abi

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/*.apk

      # Build App Bundle
      - name: Build App Bundle
        run: flutter build appbundle --release

      # Upload App Bundle artifact
      - name: Upload App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-bundle
          path: build/app/outputs/bundle/release/*.aab
